version: '3.3'

services:
  nginx:
    container_name: nginxwp
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./wp-app:/var/www/html
    links:
      - wordpress
    restart: always

  mysql:
    container_name: mariadb
    image: mariadb
    ports:
      - '3306:3306'
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    restart: always

  wordpress:
    container_name: wp
    image: wordpress:5.1.1-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./wp-app:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_PASSWORD=wordpress
    links:
      - mysql
    restart: always

